# Generated by Django 5.1 on 2024-08-15 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacitado',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('numero_patente', models.CharField(max_length=10, unique=True)),
                ('tutor_dni', models.CharField(blank=True, max_length=8, null=True)),
                ('tutor_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('tutor_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tutor_relacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('discapacitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='discapacidad.discapacitado')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=100)),
                ('discapacitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='discapacidad.discapacitado')),
            ],
        ),
    ]
