# Generated by Django 5.1 on 2024-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacitado',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
