# Generated by Django 5.1 on 2024-12-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipobien',
            name='prefijo',
            field=models.CharField(default='codinterno', max_length=10, unique=True),
        ),
    ]
