# Generated by Django 5.1 on 2024-12-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni_cuit', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('dominio', models.CharField(max_length=10, unique=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('reservado', models.BooleanField(default=False)),
            ],
        ),
    ]
