# Generated by Django 5.1 on 2024-12-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='linea',
            field=models.CharField(choices=[('livianos', 'Línea Livianos'), ('mixta', 'Línea Mixta')], default=0, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='vehiculo',
            field=models.CharField(choices=[('gol', 'Gol'), ('voyage', 'Voyage'), ('aveo', 'Aveo'), ('prisma', 'Prisma'), ('suran', 'Suran'), ('206', 'Peugeot 206'), ('207', 'Peugeot 207'), ('208', 'Peugeot 208'), ('307', 'Peugeot 307'), ('ecosport', 'Ecosport'), ('audi_a5', 'Audi A5'), ('408', 'Peugeot 408'), ('508', 'Peugeot 508'), ('hilux', 'Hilux'), ('corolla', 'Corolla')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
