# Generated by Django 5.1 on 2025-01-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authturno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_turno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
