# Generated by Django 5.1 on 2025-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authturno', '0002_turno_fecha_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_turno',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
