# Generated by Django 5.1 on 2025-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedula',
            name='dorso',
        ),
        migrations.RemoveField(
            model_name='cedula',
            name='frente',
        ),
        migrations.AddField(
            model_name='cedula',
            name='ruta_pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
