# Generated by Django 5.1 on 2025-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedulas', '0002_remove_cedula_dorso_remove_cedula_frente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedula',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
