# Generated by Django 5.1 on 2024-08-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExCombatiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('apellido_nombre', models.CharField(max_length=255)),
                ('fuerza', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=100)),
                ('condicion', models.CharField(max_length=50)),
                ('vive', models.BooleanField()),
            ],
        ),
    ]
